<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    
    public function countAll()
    {
        $count=0;
        $count=$this->createQueryBuilder('id')
                 ->select('COUNT(id)')
                ->getQuery()
                 ->getSingleScalarResult();
        return $count;
    }
}
